version: '3.8'

services:
  galveston-scraper:
    build: .
    container_name: galveston-tax-scraper
    environment:
      # Brevo Email Configuration
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL:-noreply@galvestonscraper.com}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME:-Galveston Scraper}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - NOTIFICATION_NAME=${NOTIFICATION_NAME:-Admin}
      
      # Scraper Configuration
      - SCRAPER_THREADS=${SCRAPER_THREADS:-3}
      - PYTHONPATH=/app
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      
    volumes:
      # Persist checkpoints, logs, and output
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./output:/app/output
      
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: galveston-scraper-network 